AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for Amazon S3 bucket creation and configuration

Parameters:
  BucketName: { Type: String, Default: "enter-your-bucket-name-here" }

Resources:          
  Bucket1:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  Bucket1Name:
    Description: Name of the bucket
    Value: !Ref Bucket1